- name: Verify Python installation
  win_command: python --version
  register: python_version

- name: Output Python version
  debug:
    msg: "Installed Python version is: {{ python_version.stdout }}"
