schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/ApplicationServices/MergeServices
  - name: api_sln
    value: LogixRREServices.sln
  - name: container_path_service
    value: _PublishedWebsites\LogixRREAPIService
  - name: project_name
    value: LogixNCV-MergeService
  - name: artifactname_service
    value: MergeService

stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: MergeService
        displayName: Mergeservice
        steps:
          - checkout: self
            clean: true
            path: s/LogixNCV-MS
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_48_build.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    variables:
      - name: ArtifactName
        value: MergeService
      - name: Environment
        value: DEV
      - name: SiteName
        value: LogixNCV
      - name: TargetFolder
        value: D:\TFS\Release\NCVMergeService
      - name: WebAppPoolName
        value: LogixNCV
    jobs:
      - deployment: DEV
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: cv
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    variables:
      - name: ArtifactName
        value: MergeService
      - name: Environment
        value: UAT
      - name: SiteName
        value: LogixNCV
      - name: TargetFolder
        value: D:\TFS\Release\NCVMergeService
      - name: WebAppPoolName
        value: LogixNCV
    jobs:
      - deployment: UAT
        displayName: UAT
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: cv
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    displayName: PROD
    dependsOn: UAT
    condition: ${{ variables.build_reason_condition }}
    variables:
      - name: ArtifactName
        value: MergeService
      - name: Environment
        value: PROD
      - name: TargetFolder
        value: D:\TFS\LogixNCV\Release
      - name: WebAppPoolName
        value: NCVMERGE
    jobs:
      - deployment: PROD
        displayName: PORD
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: cv
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
