variables:
  - name: app_directory
    value: apps/ConsoleApps/LogixBilling.ClaimsAppealStatus
  - name: dotnet_version
    value: 8.x
  - name: app_csproj_file
    value: LogixHealth.Service.ClaimsAppealStatus/LogixHealth.Service.ClaimsAppealStatus.csproj
  - name: project_name
    value: ClaimsAppealStatus
  # - name: test_app_csproj_file
  #   value: LogixHealth.Service.ClaimsAppealStatus.MsTests/LogixHealth.Service.ClaimsAppealStatus.MsTests.csproj
  - name: publish_appcsproj_file
    value: LogixHealth.Service.ClaimsAppealStatus/LogixHealth.Service.ClaimsAppealStatus.csproj
  - name: container_path_app
    value: LogixHealth.Service.ClaimsAppealStatus
  - name: artifactname_app
    value: ClaimsAppealStatusReport
  - name: test_app_csproj_file
    value: LogixHealth.Service.ClaimsAppealStatus.MsTests/LogixHealth.Service.ClaimsAppealStatus.MsTests.csproj
pool:
  name: Build
stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
            clean: true
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.app_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: Dev
    dependsOn: Build
    jobs:
      - deployment: ClaimsAppealStatusReport
        displayName: ClaimsAppealStatusReport
        variables:
          - name: ArtifactName
            value: ClaimsAppealStatusReport
          - name: SiteName
            value:
          - name: TargetFolder
            value: D:\AzureDevOps\ConsoleApps\ClaimsAppealStatusReport\Release
          - name: WebAppPoolName
            value:
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    dependsOn: Build
    jobs:
      - deployment: ClaimsAppealStatusReport
        displayName: ClaimsAppealStatusReport
        variables:
          - name: ArtifactName
            value: ClaimsAppealStatusReport
          - name: SiteName
            value:
          - name: TargetFolder
            value: D:\AzureDevOps\ConsoleApps\ClaimsAppealStatusReport\Release
          - name: WebAppPoolName
            value:
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    dependsOn: UAT
    jobs:
      - deployment: ClaimsAppealStatusReport
        displayName: ClaimsAppealStatusReport
        variables:
          - name: ArtifactName
            value: ClaimsAppealStatusReport
          - name: SiteName
            value:
          - name: TargetFolder
            value: D:\AzureDevOps\ConsoleApps\ClaimsAppealStatusReport\Release
          - name: WebAppPoolName
            value:
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
