schedules:
  - cron: '30 15 * * *' #10:30 EST
    displayName: Automated Python Build
    branches:
      include:
        - feature
    always: true
  - cron: '0 12 * * *' #7:00 EST
    displayName: Automated Python Build
    branches:
      include:
        - feature
    always: true
stages:
  - stage: PythonScriptRun
    displayName: Python_Script_Run
    variables:
      - name: file_path
        value: '$(Build.SourcesDirectory)\utilities\python\Billing ARA Pre Check'
      - name: file_name
        value: 'Ara_Report_Check_Mod.py'
      - name: venv_activate_path
        value: 'C:/PythonVenvs/LogixBI/Scripts/activate.ps1'
      - name: python_exe
        value: 'C:/PythonVenvs/LogixBI/Scripts/python.exe'
      - name: environment
        value: development
    pool:
      name: DEV
      demands:
        - Agent.name -equals BEDDBICDN001
    jobs:
      - job: RunPythonScript
        displayName: RunPythonScript
        steps:
          - template: ../templates/pythonscript_run.yml
