schedules:
  - cron: 0 11 * * * # UTC For - EST Daily at 6AM every day
    displayName: Automated Python Build
    branches:
      include:
        - feature
    always: true

stages:
  - stage: PythonScriptRun
    displayName: Python_Script_Run
    variables:
      - name: file_path
        value: '$(Build.SourcesDirectory)\utilities\python\Billing Month End Automation'
      - name: file_name
        value: 'Billing_ME_Report_Automation_Prod.py'
      - name: venv_activate_path
        value: 'C:/PythonVenvs/LogixBI/Scripts/activate.ps1'
      - name: python_exe
        value: 'C:/PythonVenvs/LogixBI/Scripts/python.exe'
      - name: environment
        value: development
    pool:
      name: DEV
      demands:
        - Agent.name -equals BEDDBICDN001
    jobs:
      - job: RunPythonScript
        displayName: RunPythonScript
        steps:
          - template: ../templates/pythonscript_run.yml
