schedules:
  - cron: 0 0,2,4,6,8,10,12,14,16,18,20,22 * * * # UTC For - Every 2 hours
    displayName: Automated Python Build
    branches:
      include:
        - release/logixbi/cherwell-daily-network-common
    always: true
stages:
  - stage: PythonScriptRun
    displayName: Python_Script_Run
    condition: |
      and(
        eq(variables['Build.Reason'], 'Schedule'),
        eq(variables['Build.SourceBranch'], 'refs/heads/release/logixbi/cherwell-daily-network-common')
      )
    variables:
      - name: file_path
        value: 'C:\Run_Py_Script\CherwellTicketReport'
      - name: file_name
        value: 'Cherwell_Ticket_Report_Email_Daily_Network.py'
      - name: venv_activate_path
        value: 'C:/PythonVenvs/InfraSec/Scripts/activate.ps1'
      - name: python_exe
        value: 'C:/PythonVenvs/InfraSec/Scripts/python.exe'
      - name: environment
        value: production
    pool:
      name: PROD
      demands:
        - Agent.name -equals BEDPAUTOSPRT001
    jobs:
      - job: RunPythonScript
        displayName: RunPythonScript
        steps:
          - template: ../templates/pythonscript_run.yml
