schedules:
  - cron: 0 3 * * 1 # UTC For - On every Sunday 10 PM EST
    displayName: Automated Python Build
    branches:
      include:
        - feature
    always: true

stages:
  - stage: PythonScriptRun
    displayName: Python_Script_Run
    variables:
      - name: file_path
        value: '$(Build.SourcesDirectory)\utilities\python\Published_Reports_DEV_Repository_Creator'
      - name: file_name
        value: 'Published_Reports_Dev_Repository_Creator.py'
      - name: venv_activate_path
        value: 'C:/PythonVenvs/LogixBI/Scripts/activate.ps1'
      - name: python_exe
        value: 'C:/PythonVenvs/LogixBI/Scripts/python.exe'
      - name: environment
        value: development
    pool:
      name: DEV
      demands:
        - Agent.name -equals BEDDBICDN001
    jobs:
      - job: RunPythonScript
        displayName: RunPythonScript
        steps:
          - template: ../templates/pythonscript_run.yml
