trigger: none
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: Billing_Month_End_Automation
        displayName: Billing_Month_End_Automation
        steps:
          - checkout: self
            path: s/Billing_Month_End_Automation
            clean: true
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact'
            inputs:
              PathtoPublish: 'utilities/python/Billing Month End Automation'
              ArtifactName: 'Billing Month End Automation'
              publishLocation: 'Container'
          - template: ../templates/remove_sonarqube.yml
          - template: ../templates/delete_build_files.yml
  - stage: PROD
    dependsOn: Build
    jobs:
      - deployment: PROD
        displayName: PROD
        environment: PROD
        pool:
          name: PROD
          demands: Agent.Name -equals BEDBICDN001
        strategy:
          runOnce:
            deploy:
              steps:
                - task: PowerShell@2
                  displayName: Delete Old Files
                  condition: succeededOrFailed()
                  inputs:
                    targetType: inline
                    script: |
                      Remove-Item 'C:\PythonScripts\Billing Month End Automation\Testing\Billing_ME_Report_Automation.py'
                      Remove-Item 'C:\PythonScripts\Billing Month End Automation\CallActivate.bat'
                      Remove-Item 'C:\PythonScripts\Billing Month End Automation\CallBillingMEAutomation.bat'
                      Remove-Item 'C:\PythonScripts\Billing Month End Automation\Billing_ME_Report_Automation_Prod.py'
                - task: DownloadBuildArtifacts@0
                  inputs:
                    artifactName: 'Billing Month End Automation'
                    downloadType: single
                    downloadPath: C:\PythonScripts\
