schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    variables:
      - name: SonarQube_Condition
        value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
      - name: app_directory
        value: apps/mvc/LogixCCV
      - name: app_sln
        value: LogixClientChartViewer.sln
      - name: project_name
        value: LogixCCV
      - name: container_path_app
        value: _PublishedWebsites/LogixClientChartViewer
      - name: artifactname_app
        value: LogixCCV
    jobs:
      - job: LogixCCV_Build
        displayName: LogixCCV_Build
        steps:
          - checkout: self
            clean: true
            path: s/Logixccv
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.app_directory }}
          - template: ../templates/dotnetframework_48_build.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    jobs:
      - deployment: DEV
        variables:
          - name: ArtifactName
            value: LogixCCV
          - name: SiteName
            value: LogixCCV
          - name: WebAppPoolName
            value: LogixCCV
          - name: TargetFolder
            value: D:\TFS\Release
          - name: Environment
            value: DEV
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: ICER-WEB-DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    jobs:
      - deployment: UAT
        variables:
          - name: ArtifactName
            value: LogixCCV
          - name: SiteName
            value: LogixCCV
          - name: WebAppPoolName
            value: LogixCCV
          - name: TargetFolder
            value: D:\TFS\Release
          - name: Environment
            value: UAT
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: ICER-WEB-UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    displayName: PROD
    dependsOn: UAT
    jobs:
      - deployment: PROD
        variables:
          - name: ArtifactName
            value: LogixCCV
          - name: SiteName
            value: LogixChartview(CCV)
          - name: WebAppPoolName
            value: LogixChartview(CCV)
          - name: TargetFolder
            value: D:\TFS\Release
          - name: Environment
            value: PROD
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: CCV
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
