# AzureArc install and onboarding
- name: Skip Azure Arc role in check mode
  meta: end_play
  when: ansible_check_mode

- name: Check if the Connected Machine Agent has already been downloaded on Windows servers
  win_stat:
    path: C:\Program Files\AzureConnectedMachineAgent
  register: azcmagent_win_downloaded

- name: Download the Connected Machine Agent on Windows servers
  win_get_url:
    url: https://aka.ms/AzureConnectedMachineAgent
    dest: C:\AzureConnectedMachineAgent.msi
  when: not azcmagent_win_downloaded.stat.exists

- name: Install the Connected Machine Agent on Windows servers
  win_package:
    path: C:\AzureConnectedMachineAgent.msi
  when: not azcmagent_win_downloaded.stat.exists

- name: Check if the Connected Machine Agent has already been connected on windows
  win_command: azcmagent check
  register: azcmagent_win_connected
  ignore_errors: yes
  failed_when: (azcmagent_win_connected.rc not in [ 0, 16 ])
  changed_when: False

- name: Connect the Connected Machine Agent on Windows servers to Azure
  win_shell: '& $env:ProgramFiles\AzureConnectedMachineAgent\azcmagent.exe connect --service-principal-id "{{ az_arc_service_principal_id }}" --service-principal-secret "{{ az_arc_service_principal_secret }}" --resource-group "{{ az_arc_resource_group }}" --tenant-id "{{ az_arc_tenant_id }}" --location "{{ az_arc_location }}" --subscription-id "{{ az_arc_subscription_id }}" --verbose'
  when: azcmagent_win_connected.rc is defined and azcmagent_win_connected.rc != 0
