trigger: none

pool: Build
variables:
  exit_check: if ($LASTEXITCODE -ne 0){Write-Host “##vso[task.complete result=Failed;]”; exit 1}
  terraform_fmt_check: terraform -chdir=terraform fmt -recursive -check;${{ variables.exit_check }}
  terragrunt_hclfmt_check: terragrunt hclfmt --terragrunt-check --terragrunt-working-dir terraform/deployments;${{ variables.exit_check }}
  plan_task_format_check: ${{ variables.terraform_fmt_check }};${{ variables.terragrunt_hclfmt_check }}
  terragrunt_validate_inputs: terragrunt validate-inputs --terragrunt-strict-validate

stages:
  - stage: sandbox
    variables:
      - group: pipeline
    jobs:
      - job: sandbox_plan
        displayName: Azure Sandbox Plan
        steps:
          - template: ../../0_Global_Library/pipeline-templates/tasks/terraform_v1_install_task.yml
          - task: PowerShell@2
            displayName: Sandbox Plan Astro
            inputs:
              targetType: inline
              pwsh: true
              script: |
                ${{ variables.plan_task_format_check }}
                ${{ variables.terragrunt_validate_inputs }} --terragrunt-working-dir terraform/deployments/sbox/astro
                ${{ variables.exit_check }}
                terragrunt run-all plan --terragrunt-working-dir terraform/deployments/sbox/astro
            env:
              ARM_CLIENT_ID: $(client_id_sbox)
              ARM_CLIENT_SECRET: $(client_secret_sbox)
              ARM_TENANT_ID: $(tenant_id)
      - job: sandbox_approve
        displayName: Azure Sandbox Approve TF
        dependsOn: sandbox_plan
        pool: server
        timeoutInMinutes: 4320 # 3 days
        steps:
          - task: ManualValidation@0
            inputs:
              notifyUsers: ""
      - job: sandbox_apply
        displayName: Azure Sandbox Apply
        dependsOn: sandbox_approve
        steps:
          - template: ../../0_Global_Library/pipeline-templates/tasks/terraform_v1_install_task.yml
          - task: PowerShell@2
            displayName: Sandbox Apply Astro
            inputs:
              targetType: inline
              pwsh: true
              script: |
                terragrunt run-all apply --terragrunt-non-interactive --terragrunt-working-dir terraform/deployments/sbox/astro
            env:
              ARM_CLIENT_ID: $(client_id_sbox)
              ARM_CLIENT_SECRET: $(client_secret_sbox)
              ARM_TENANT_ID: $(tenant_id)
