schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: app_directory
    value: apps/mvc/LogixConnect
  - name: app_sln
    value: LogixHealth.Connect.Portal.sln
  - name: project_name
    value: LogixConnect-Application
  - name: container_path_app
    value: _PublishedWebsites\LogixHealth.Connect.Web
  - name: artifactname_app
    value: connectPortal
  - name: app_test_csproj
    value: Logixhealth.Connect.Web.Tests/Logixhealth.Connect.Web.Tests.csproj
  - name: App_Test_dll_path
    value: Logixhealth.Connect.Web.Tests.dll
  - name: autoproject
    value: ConnectPlaywright
  - name: dtesturl
    value: 'https://devlhconnect.logixhealth.com/connectportal'
  - name: utesturl
    value: 'https://uconnect.logixhealth.com/connectportal'
  - name: ptesturl
    value: 'https://connect.logixhealth.com/connectportal'
  - name: RegressionSuite
    value: 'regression.xml'
  - name: SanitySuite
    value: 'sanity.xml'
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
            path: s/LogixConnect
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.app_directory }}
          - template: ../templates/dotnetframework_48_build.yml
  - stage: LogixConnectEntraDemo
    displayName: LogixConnect Entra Demo
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - job: Approve_To_LogixConnectEntraDemo
        displayName: Approval for LogixConnectEntraDemo
        pool: server
        steps:
          - task: ManualValidation@0
            inputs:
              notifyUsers: 'tvenugopal@logixhealth.com'
              instructions: 'Please Approve or Reject the Config Management changes to the DEV Environment.'
      - deployment: LC_Legacy_Portal
        displayName: LC-Legacy-Portal
        dependsOn: Approve_To_LogixConnectEntraDemo
        variables:
          - name: ArtifactName
            value: connectPortal
          - name: Environment
            value: Dev
          - name: SiteName
            value: d1connect.logixhealth.com
          - name: TargetFolder
            value: D:\TFSReleases\d1connect.logixhealth.com\ConnectPortal
          - name: WebAppPoolName
            value: d1connect.logixhealth.com
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: DEV
    displayName: Development
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: LC_Legacy_Portal
        displayName: LC-Legacy-Portal
        variables:
          - name: ArtifactName
            value: connectPortal
          - name: Environment
            value: Dev
          - name: SiteName
            value: devlhconnect.logixhealth.com
          - name: TargetFolder
            value: D:\TFS\LogixConnect\ConnectPortal
          - name: WebAppPoolName
            value: LogixConnect
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: LC_Legacy_Portal
        displayName: LC-Legacy-Portal
        variables:
          - name: ArtifactName
            value: connectPortal
          - name: Environment
            value: UAT
          - name: SiteName
            value: LogixConnect
          - name: TargetFolder
            value: D:\TFS\LogixConnect\ConnectPortal
          - name: WebAppPoolName
            value: LogixConnect
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: Training
    displayName: TRAINING
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: LC_Legacy_Portal
        displayName: LC-Legacy-Portal
        variables:
          - name: ArtifactName
            value: connectPortal
          - name: Environment
            value: TRAINING
          - name: SiteName
            value: LogixConnect
          - name: TargetFolder
            value: D:\TFS\LogixConnect\ConnectPortal
          - name: WebAppPoolName
            value: LogixConnect
        environment:
          name: TRAINING
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    displayName: PROD_connectPortal
    dependsOn: UAT
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: LC_Legacy_Portal
        displayName: LC-Legacy-Portal
        variables:
          - name: ArtifactName
            value: connectPortal
          - name: Environment
            value: Prod
          - name: SiteName
            value: LogixConnect
          - name: TargetFolder
            value: D:\TFS\LogixConnect\ConnectPortal
          - name: WebAppPoolName
            value: LogixConnect
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: ops
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
