schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/ApplicationServices/LogixConnect-IDPServices
  - name: api_sln
    value: LogixHealth.IDP.sln
  - name: project_name
    value: LogixConnectIDP-Services
  - name: container_path_app
    value: _PublishedWebsites\LogixHealth.IdentityProvider
  - name: container_path_service
    value: _PublishedWebsites\LogixHealth.IdentityProviderServices
  - name: artifactname_app
    value: IdentityProvider
  - name: artifactname_service
    value: IdentityProviderServices
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: IdentityProviderServices
        displayName: IDP-Services
        steps:
          - checkout: self
            path: s/IDPServices
            clean: true
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_48_build.yml
  - stage: DEVIDP
    displayName: DEV_IDPDeployment
    dependsOn: Build
    condition: and(succeeded() ,${{ variables.build_reason_condition }} )
    jobs:
      - deployment: DEV
        displayName: Dev
        variables:
          - name: ArtifactName
            value: IdentityProvider
          - name: Environment
            value: DEV
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\IdentityProvider\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: DEVIDPService
    displayName: DEV_IDPSVC-Deployment
    dependsOn: DEVIDP
    condition: and(succeeded() ,${{ variables.build_reason_condition }} )
    jobs:
      - deployment: DEV
        displayName: Dev
        variables:
          - name: ArtifactName
            value: IdentityProviderServices
          - name: Environment
            value: DEV
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\IdentityProviderServices\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UATIDP
    displayName: UAT_IDPDeployment
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        displayName: UAT
        variables:
          - name: ArtifactName
            value: IdentityProvider
          - name: Environment
            value: UAT
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\TFS\LogixServices_new\LogixIDP\IDPApplication
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UATIDPService
    displayName: UAT_IDPSVCDeployment
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        displayName: UAT
        variables:
          - name: ArtifactName
            value: IdentityProviderServices
          - name: Environment
            value: UAT
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\TFS\LogixServices_new\LogixIDP\IDPServices
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: TRAININGIDP
    displayName: TRAINING_IDPDeployment
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: TRAINING
        displayName: Training
        variables:
          - name: ArtifactName
            value: IdentityProvider
          - name: Environment
            value: TRAINING
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\TFS1\LogixIDP\IDPApplication
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: Training
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: TRAININGIDPService
    displayName: TRAINING_IDPSVCDeployment
    dependsOn: TRAININGIDP
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: TRAINING
        displayName: Training
        variables:
          - name: ArtifactName
            value: IdentityProviderServices
          - name: Environment
            value: TRAINING
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\TFS1\LogixIDP\IDPServices
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: Training
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PRODIDP
    displayName: PROD_IDPDeployment
    dependsOn: UATIDP
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD
        displayName: PROD
        variables:
          - name: ArtifactName
            value: IdentityProvider
          - name: Environment
            value: Prod
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\TFS\LogixIDP\IDPApplication\
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: ops
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PRODIDPService
    displayName: PROD_IDPSVC-Deployment
    dependsOn: UATIDPService
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD
        displayName: PROD
        variables:
          - name: ArtifactName
            value: IdentityProviderServices
          - name: Environment
            value: Prod
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\TFS\LogixIDP\IDPServices\
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: ops
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
