# This pipeline checks to see if every new commit contains properly formatted Terraform code.

trigger:
  paths:
    include:
      - "*.tf"

pool: BuildLinux

stages:
  - stage: terraform_fmt
    jobs:
      - job: terraform_fmt
        displayName: Terraform Auto-Format Check
        steps:
          - template: ../0_Global_Library/pipeline-templates/tasks/terraform_v2_install_task.yml

          - task: Bash@3
            displayName: Get changed files
            inputs:
              targetType: inline
              script: |
                CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD -- '*.tf')
                echo "##vso[task.setvariable variable=CHANGED_FILES]$CHANGED_FILES"

          - task: Bash@3
            displayName: Run terraform-fmt on changed files
            inputs:
              targetType: inline
              script: |
                if [ -n "$CHANGED_FILES" ]; then
                  echo "Ensuring that changed Terraform files are still formatted with \"terraform fmt\"..."
                  echo "$CHANGED_FILES" | xargs terraform fmt -check
                  echo "All changed files are correctly formatted."
                else
                  echo "No changed terraform files."
                fi
