#Variable values for data disks
data_disks:
  - disk_number: 1
    drive_letter: L
    disk_label: LDF
    allocation_unit_size: 65536 #64k
  - disk_number: 2
    drive_letter: M
    disk_label: MDF
    allocation_unit_size: 65536
  - disk_number: 3
    drive_letter: T
    disk_label: TempDB
    allocation_unit_size: 65536

#Server access values
rdp_access_group_name: CORP\SRV_BEDITEST_RDP
admin_access_group_name: CORP\SRV_BEDITEST_Admin
