---
#AzDO Agent Info
azdo_agent_service_name: vstsagent.azuredevops.PROD.BED_PSVC001
azdo_agent_service_account: CORP\svc_azdo_prod
azdo_agent_service_password: $(prod_azdo_agent_service_password)

#Application Insights
app_insights_connection_string: "InstrumentationKey=79086e48-f35f-4af1-8491-08cda98abe44;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com/;LiveEndpoint=https://eastus.livediagnostics.monitor.azure.com/;ApplicationId=40512c13-b124-4ad4-89a5-fa25fd6a8e53"

iis_website_app_info:
  - app_pool_name: mobilepay.microsvc.logixhealth.com
    website_state: started
    gMSA: CORP\gmsa_mobpayapi$
    mpl_mode: Integrated
    runtime_version: ""
    root_path: D:\TFS\MicroServices\Atomic\MobilePay\Release\MobilePayAPI
    website_name: mobilepay.microsvuc.logixhealth.com
    host_name: mobilepay.microsvuc.logixhealth.com
    thumbprint_value: be9a088bba11bde4361d5fa844f4e2fd161a8723
#   - app_pool_name: cpm.microsvc.logixhealth.com
#     website_state: started
#     gMSA: CORP\
#     mpl_mode: Integrated
#     runtime_version: ""
#     website_name: cpm.microsvc.logixhealth.com
#     host_name: cpm.microsvc.logixhealth.com
#     root_path: D:\TFS\MicroServices\Atomic\CPM\Release\CPM
#     thumbprint_value: 01937181cb075c9b0f6625ad2679cd733bbcdaf0
#   - app_pool_name: refunds.microsvc.logixhealth.com
#     website_state: started
#     gMSA: CORP\
#     mpl_mode: Integrated
#     runtime_version: ""
#     website_name: refunds.microsvc.logixhealth.com
#     host_name: refunds.microsvc.logixhealth.com
#     root_path: D:\TFS\MicroServices\Atomic\Refunds\Release\LogixRefundsAPI
#     thumbprint_value: 01937181cb075c9b0f6625ad2679cd733bbcdaf0
#   - app_pool_name: reportingdm.microsvc.logixhealth.com
#     website_state: started
#     gMSA: CORP\
#     mpl_mode: Integrated
#     runtime_version: ""
#     website_name: reportingdm.microsvc.logixhealth.com
#     host_name: reportingdm.microsvc.logixhealth.com
#     root_path: D:\TFS\MicroServices\Atomic\ReportingDM\Release\ReportingDM
#     thumbprint_value: 01937181cb075c9b0f6625ad2679cd733bbcdaf0
#   - app_pool_name: refunds.orchsvc.logixhealth.com
#     website_state: started
#     gMSA: CORP\
#     mpl_mode: Integrated
#     runtime_version: ""
#     website_name: refunds.orchsvc.logixhealth.com
#     host_name: refunds.orchsvc.logixhealth.com
#     root_path: D:\AzureDevOps\APIServices\Orchestration\Refunds\Release\OrchRefunds
#     thumbprint_value: 9ecbc9a59088f07f6e17e3051a64fc15e4374202
#Variable values for all Windows Services Apps
windows_service_app_info:
  - service_name: LogixAvailityFileWatcher
    gMSA: CORP\gmsa_availfw$

#AD Group used to manage service accounts needed to run Windows Services Apps
logon_as_a_service_AD_group: CORP\PROD_Microservice_Windows_Services
#Scheduled Task Info for Claims Appeal Daily & Status Reports
# sched_task_info:
#   - task_name: LogixHealth Claims Appeal Daily Summary Report
#     task_descrip: LogixHealth Claims Appeal Daily Summary Report Job for Billing team's UHC worker service
#     task_exe: D:\AzureDevOps\ConsoleApps\ClaimsAppealDailySummaryReport\Release\ClaimsAppealDailySummaryReport\LogixHealth.App.AppealDailyReport.exe
#     task_sched_type: daily
#     task_sched_time: "2024-07-26T00:15:00"
#     task_gmsa: CORP\gmsa_claimsum$
#     logon_type: password
#     run_level: highest
#     enabled_flag: true
#   - task_name: LogixHealth Daily Claims Status Report
#     task_descrip: LogixHealth Daily Claims Status Report Job for Billing team's UHC worker service
#     task_exe: D:\AzureDevOps\ConsoleApps\ClaimsAppealStatusReport\Release\ClaimsAppealStatusReport\LogixHealth.Service.ClaimsAppealStatus.exe
#     task_sched_type: daily
#     task_sched_time: "2024-07-26T00:30:00"
#     task_gmsa: CORP\gmsa_claimstat$
#     logon_type: password
#     run_level: highest
#     enabled_flag: true

# rootpathsubs:
#   - path: 'D:\TFS\MicroServices\Atomic\CPM\Release\CPM'
#   - path: 'D:\TFS\MicroServices\Atomic\Refunds\Release\LogixRefundsAPI'
#   - path: 'D:\AzureDevOps\APIServices\Orchestration\Refunds\Release\OrchRefunds'
#   - path: 'D:\TFS\MicroServices\Atomic\ReportingDM\Release\ReportingDM'
