schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/ApplicationServices/LogixConnectServices
  - name: api_sln
    value: LogixHealth.Connect.PortalServices.sln
  - name: project_name
    value: LogixConnect-PortalServices
  - name: container_path_service
    value: _PublishedWebsites\LogixHealth.Connect.Services
  - name: artifactname_service
    value: connectPortalServices
  - name: autoproject
    value: ConnectPlaywright
  - name: dtesturl
    value: 'https://devlhconnect.logixhealth.com/connectportal'
  - name: utesturl
    value: 'https://uconnect.logixhealth.com/connectportal'
  - name: ptesturl
    value: 'https://connect.logixhealth.com/connectportal'
  - name: RegressionSuite
    value: 'regression.xml'
  - name: SanitySuite
    value: 'sanity.xml'
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
            path: s/LogixConnect
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_48_build.yml
  - stage: LogixConnectEntraDemo
    displayName: LogixConnect Entra Demo
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - job: Approve_To_LogixConnectEntraDemo
        displayName: Approval for LogixConnectEntraDemo
        pool: server
        steps:
          - task: ManualValidation@0
            inputs:
              notifyUsers: 'tvenugopal@logixhealth.com'
              instructions: 'Please Approve or Reject the Config Management changes to the DEV Environment.'
      - deployment: LC_Legacy_SVC
        displayName: LC-Legacy-Services
        variables:
          - name: ArtifactName
            value: connectPortalServices
          - name: Environment
            value: Dev
          - name: SiteName
            value: d1connect.logixhealth.com
          - name: TargetFolder
            value: D:\TFSReleases\d1connect.logixhealth.com\ConnectPortalServices
          - name: WebAppPoolName
            value: d1connect.logixhealth.com
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: DEV
    displayName: Development
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: LC_Legacy_SVC
        displayName: LC-Legacy-Services
        variables:
          - name: ArtifactName
            value: connectPortalServices
          - name: Environment
            value: Dev
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\ConnectPortalServices\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: LogixSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: LC_Legacy_SVC
        displayName: LC-Legacy-Services
        variables:
          - name: ArtifactName
            value: connectPortalServices
          - name: Environment
            value: UAT
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\ConnectPortalServices\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: LogixSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: Training
    displayName: TRAINING
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: LC_Legacy_SVC
        displayName: LC-Legacy-Services
        variables:
          - name: ArtifactName
            value: connectPortalServices
          - name: Environment
            value: TRAINING
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\ConnectPortalServices\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: TRAINING
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    displayName: PROD_service
    dependsOn: UAT
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: LC_Legacy_Portal_SVC
        displayName: LC-Legacy-Portal-Services
        variables:
          - name: ArtifactName
            value: connectPortalServices
          - name: Environment
            value: Prod
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\ConnectPortalServices\Release
          - name: WebAppPoolName
            value: LogixConnectServices
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: LogixSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
