# schedules:
#   - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
#     displayName: Automated SonarQube Build
#     branches:
#       include:
#         - master
#     always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/ApplicationServices/LogixServices-IVR
  - name: api_sln
    value: WCFSolution.sln
  - name: project_name
    value: LogixServices-ApiIVR
  - name: container_path_service
    value: _PublishedWebsites\Logixhealth.Verification.WebApi
  - name: artifactname_service
    value: ApiIVR
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
            path: s/IVR
            clean: true
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_48_build.yml
  - stage: DEV
    displayName: DEV_ApiIVR
    dependsOn: Build
    jobs:
      - deployment: DEV_ApiIVR
        displayName: DEV_ApiIVR
        variables:
          - name: ArtifactName
            value: ApiIVR
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\ApiVR\Release
          - name: WebAppPoolName
            value: LogixServices-ApiIVR
          - name: Environment
            value: DEV
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT_ApiIVR
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT_ApiIVR
        displayName: UAT_ApiIVR
        variables:
          - name: ArtifactName
            value: ApiIVR
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\ApiVR\Release
          - name: WebAppPoolName
            value: LogixServices-ApiIVR
          - name: Environment
            value: UAT
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    displayName: PROD_ApiIVR
    dependsOn: UAT
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD_ApiIVR
        displayName: PROD_ApiIVR
        variables:
          - name: ArtifactName
            value: ApiIVR
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\ApiVR\Release
          - name: WebAppPoolName
            value: LogixServices-ApiIVR
          - name: Environment
            value: PROD
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml