# schedules:
#   - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
#     displayName: Automated SonarQube Build
#     branches:
#       include:
#         - master
#     always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/ApplicationServices/LogixServices-IVR
  - name: api_csproj_file
    value: LogixHealth.IVR/LogixHealth.IVR.sln
  - name: project_name
    value: LogixServices-IVR
  - name: container_path_api
    value: LogixHealth.IVR
  - name: publish_apicsproj_file
    value: LogixHealth.IVR/LogixHealth.IVR/LogixHealth.IVR.csproj
  # - name: test_csproj_file
  #   value: LogixHealth.IVR/LogixHealth.IVR.Tests/LogixHealth.IVR.Tests.csproj
  - name: artifactname_api
    value: ApiIVR
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
            path: s/IVR
            clean: true
          # - template: ../templates/prebuild_validation.yml
          #   parameters:
          #     directoryPaths:
          #       - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        variables:
          - name: ArtifactName
            value: ApiIVR
          - name: SiteName
            value: billing.dmicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\ApiVR\Release
          - name: WebAppPoolName
            value: LogixServices-IVR
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        variables:
          - name: ArtifactName
            value: ApiIVR
          - name: SiteName
            value: billing.umicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\ApiVR\Release
          - name: WebAppPoolName
            value: LogixServices-IVR
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    displayName: PROD
    dependsOn: UAT
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD
        variables:
          - name: ArtifactName
            value: ApiIVR
          - name: SiteName
            value: billing.microsvc.logixhealth.com
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\ApiVR\Release
          - name: WebAppPoolName
            value: LogixServices-IVR
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
