schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/ApplicationServices/LogixConnect-IDPServices
  - name: api_sln
    value: LogixHealth.IDP.sln
  - name: project_name
    value: LogixConnectIDP-Services
  - name: container_path_service
    value: _PublishedWebsites\LogixHealth.IdentityProviderServices
  - name: container_path_app
    value: _PublishedWebsites\LogixHealth.IdentityProvider
  - name: artifactname_app
    value: IdentityProvider
  - name: artifactname_service
    value: IdentityProviderServices
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: IdentityProviderServices
        displayName: IDP-Services
        steps:
          - checkout: self
            path: s/IDPServices
            clean: true
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_48_build.yml
  - stage: DEV_IDP
    displayName: DEV_IDP
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV_IDP
        displayName: DEV_IDP
        variables:
          - name: ArtifactName
            value: IdentityProvider
          - name: Environment
            value: DEV
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\IdentityProvider\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: LogixSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: DEV_IDP_Service
    displayName: DEV_IDP_Service
    dependsOn: DEV_IDP
    jobs:
      - deployment: DEV_IDP_Service
        displayName: DEV_IDP_Service
        variables:
          - name: ArtifactName
            value: IdentityProviderServices
          - name: Environment
            value: DEV
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\IdentityProviderServices\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: LogixSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT_IDP
    displayName: UAT_IDP
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT_IDP
        displayName: UAT_IDP
        variables:
          - name: ArtifactName
            value: IdentityProvider
          - name: Environment
            value: UAT
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\IdentityProvider\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: LogixSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT_IDP_Service
    displayName: UAT_IDP_Service
    dependsOn: UAT_IDP
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT_IDP_Service
        displayName: UAT_IDP_Service
        variables:
          - name: ArtifactName
            value: IdentityProviderServices
          - name: Environment
            value: UAT
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\IdentityProviderServices\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: LogixSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD_IDP
    displayName: PROD_IDP
    dependsOn: UAT_IDP_Service
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD_IDP
        displayName: PROD_IDP
        variables:
          - name: ArtifactName
            value: IdentityProvider
          - name: Environment
            value: PROD
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\IdentityProvider\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: LogixSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD_IDP_Service
    displayName: PROD_IDP_Service
    dependsOn: PROD_IDP
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD_IDP_Service
        displayName: PROD_IDP_Service
        variables:
          - name: ArtifactName
            value: IdentityProviderServices
          - name: Environment
            value: PROD
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\IdentityProviderServices\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: LogixSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
