trigger: none
schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: release_branch_condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/release/')
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: autoproject
    value: WebsitePlaywright
  - name: dtesturl
    value: 'https://dlogixhealth.logixhealth.com'
  - name: qtesturl
    value: 'https://qlogixhealth.logixhealth.com'
  - name: utesturl
    value: 'https://ulogixhealth.logixhealth.com'
  - name: ptesturl
    value: 'https://www.logixhealth.com'
  - name: app_directory
    value: apps/mvc/website
  - name: api_directory
    value: platform/API/ApplicationServices/LogixhealthCorpsiteAPI/LogixhealthCorpsiteAPI
  - name: dotnet_version
    value: 8.x
  - name: app_csproj_file
    value: LogixHealthWebsite.csproj
  - name: api_csproj_file
    value: LogixhealthCorpsiteAPI.csproj
  - name: test_csproj_file
    value: ../LogixhealthCorpsiteTest/LogixhealthCorpsiteTest.csproj
  - name: project_name
    value: LogixWebsite
  - name: publish_appcsproj_file
    value: LogixHealthWebsite.csproj
  - name: publish_apicsproj_file
    value: LogixhealthCorpsiteAPI.csproj
  - name: container_path_app
    value: APP
  - name: container_path_api
    value: API/LogixhealthCorpsiteAPI
  - name: artifactname_app
    value: Release
  - name: artifactname_api
    value: WebsiteAPI
  - name: publish_path_app
    value: APP
  - name: publish_path_api
    value: API
stages:
  - stage: Build
    pool:
      name: Build
    jobs:
      - job: Build
        displayName: Build Website Project
        steps:
          - checkout: self
            clean: true
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
                - ${{ variables.app_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: azure_sandbox
    pool:
      name: Build
    dependsOn: [] # Run this stage immediately (instead of being dependant upon the previous step).
    jobs:
      - deployment: azure_sandbox
        displayName: Azure Sandbox
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/delete_build_files.yml
                - checkout: self
                - task: PowerShell@2
                  displayName: Validate format of dotnet project
                  inputs:
                    targetType: inline
                    pwsh: true1
                    script: |
                      cd apps/mvc/website
                      dotnet format --verify-no-changes
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: LH Sandbox Data MG
                    scriptType: pscore
                    scriptLocation: inlineScript
                    inlineScript: |
                      cd apps/mvc/website
                      $short_hash = '$(Build.SourceVersion)'.subString(0, 7)
                      az acr build --resource-group rg-data-sbox --registry lhacrsbox -t lhcorpwebsite:$short_hash --file ./Dockerfile .
                      az containerapp update -n website-sbox -g rg-data-sbox --image lhacrsbox.azurecr.io/lhcorpwebsite:$short_hash --revision-suffix $short_hash
                    useGlobalConfig: true
                - template: ../templates/remove_sonarqube.yml
                - template: ../templates/delete_build_files.yml
  - stage: DEV
    dependsOn: Build
    jobs:
      - deployment: DEV_WEB
        displayName: DEV_WEB
        variables:
          - name: ArtifactName
            value: Release
          - name: SiteName
            value: LogixHealth
          - name: TargetFolder
            value: D:\AzureDevOps\CorpWebsite
          - name: WebAppPoolName
            value: LogixHealth
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
      - deployment: DEV_APP
        displayName: DEV_APP
        dependsOn: DEV_WEB
        variables:
          - name: ArtifactName
            value: WebsiteAPI
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\TFS\Website-API/Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: azure_dev
    pool:
      name: Build
    dependsOn: azure_sandbox
    jobs:
      - deployment: azure_dev
        displayName: Azure Dev
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/delete_build_files.yml
                - checkout: self
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: LH Dev Subscription
                    scriptType: pscore
                    scriptLocation: inlineScript
                    inlineScript: |
                      cd apps/mvc/website
                      $short_hash = '$(Build.SourceVersion)'.subString(0, 7)
                      az acr build --resource-group rg-data-dev --registry lhacrdev -t lhcorpwebsite:$short_hash --file ./Dockerfile .
                    useGlobalConfig: true
                - template: ../templates/delete_build_files.yml
  - stage: UAT
    dependsOn: Build
    condition: ${{ variables.release_branch_condition }}
    jobs:
      - deployment: UAT_WEB
        displayName: UAT_WEB
        variables:
          - name: ArtifactName
            value: Release
          - name: SiteName
            value: LogixHealth
          - name: TargetFolder
            value: D:\AzureDevOps\CorpWebsite
          - name: WebAppPoolName
            value: LogixHealth
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
      - deployment: UAT_APP
        displayName: UAT_APP
        dependsOn: UAT_WEB
        variables:
          - name: ArtifactName
            value: WebsiteAPI
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\TFS\Website-API\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT_Smoke_Tests
    displayName: UAT_Smoke_Tests
    dependsOn: UAT
    pool:
      name: QAAUTO
    jobs:
      - deployment: Run_Smoke_Tests
        displayName: Run_Smoke_Tests
        environment: UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  path: s\
                  clean: true
                - task: PowerShell@2
                  displayName: Execute Smoke Test
                  inputs:
                    targetType: filePath
                    filepath: 'test\automation\Execute-Test-Automation.ps1'
                    arguments: >
                      -appdir $(autoproject)
                      -env $(utesturl)
  - stage: PROD
    dependsOn: UAT
    condition: ${{ variables.release_branch_condition }}
    jobs:
      - deployment: PROD_WEB
        displayName: PROD_WEB
        variables:
          - name: ArtifactName
            value: Release
          - name: SiteName
            value: LogixHealth
          - name: TargetFolder
            value: D:\AzureDevOps\CorpWebsite
          - name: WebAppPoolName
            value: LogixHealth
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: ops
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
      - deployment: PROD_APP
        displayName: PROD_APP
        dependsOn: PROD_WEB
        variables:
          - name: ArtifactName
            value: WebsiteAPI
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\TFS\Website-API\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: ops
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
