trigger: none
schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: release_branch_condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/release/')
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: dotnet_version
    value: 8.x
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
stages:
  - stage: Build_API
    displayName: Build_API
    pool:
      name: Build
    variables:
      - name: api_directory
        value: platform/API/ApplicationServices/LogixhealthCorpsiteAPI/LogixhealthCorpsiteAPI
      - name: api_csproj_file
        value: LogixhealthCorpsiteAPI.csproj
      - name: project_name
        value: LogixWebsiteApi
      - name: publish_apicsproj_file
        value: LogixhealthCorpsiteAPI.csproj
      - name: container_path_api
        value: API/LogixhealthCorpsiteAPI
      - name: artifactname_api
        value: WebsiteAPI
      - name: publish_path_api
        value: API
      - name: test_csproj_file
        value: ../LogixhealthCorpsiteTest/LogixhealthCorpsiteTest.csproj
    jobs:
      - job: WebsiteApi
        displayName: WebsiteApi
        steps:
          - checkout: self
            clean: true
            path: s/LogixWebsiteApi
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: DEV_API
    displayName: DEV_API
    dependsOn: Build_API
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        displayName: DEV
        variables:
          - name: ArtifactName
            value: WebsiteAPI
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\WebsiteAPI\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT_API
    displayName: UAT_API
    dependsOn: Build_API
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        displayName: UAT
        variables:
          - name: ArtifactName
            value: WebsiteAPI
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\WebsiteAPI\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD_API
    displayName: PROD_API
    dependsOn: UAT_API
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD
        displayName: PROD
        variables:
          - name: ArtifactName
            value: WebsiteAPI
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\WebsiteAPI\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: ops
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
