schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/ApplicationServices/LogixStaffingApi
  - name: api_csproj_file
    value: LogixStaffingApi/LogixStaffingApi.csproj
  - name: project_name
    value: LogixStaffing-Api
  - name: publish_apicsproj_file
    value: LogixStaffingApi/LogixStaffingApi.csproj
  - name: artifactname_api
    value: Staffing_Api
  - name: test_csproj_file
    value: LogixStaffingApiTest/LogixStaffingApiTest.csproj
  - name: container_path_api
    value: LogixStaffingApi
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: Build
        steps:
          - checkout: self
            clean: true
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        variables:
          - name: ArtifactName
            value: Staffing_Api
          - name: SiteName
            value: StaffingApi
          - name: TargetFolder
            value: D:\TFS\StaffingApi
          - name: WebAppPoolName
            value: StaffingApi
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
