# schedules:
#   - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
#     displayName: Automated SonarQube Build
#     branches:
#       include:
#         - master
#     always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/ApplicationServices/LogixConnectHeaderServices
  - name: api_sln
    value: LogixConnectHeaderServices.sln
  - name: project_name
    value: LogixConnect-Legacy-HF
  - name: test_csproj
    value: LogixHealth.Common.Services.Tests/LogixHealth.Common.Services.Tests.csproj
  - name: Test_dll_path
    value: LogixHealth.Connect.Services.Tests.dll
  - name: container_path_service
    value: _PublishedWebsites\LogixHealth.Common.Services
  - name: artifactname_service
    value: connectPortalCommonServices
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
            path: s/LogixConnect
          - template: ../templates/dotnetframework_48_build.yml
  - stage: DEV_CommonHeader_Footer
    displayName: DEV_CommonHeader_Footer
    dependsOn: Build
    jobs:
      - deployment: DEV_CommonHeader_Footer
        displayName: DEV_CommonHeader_Footer
        variables:
          - name: ArtifactName
            value: connectPortalCommonServices
          - name: Environment
            value: Dev
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\Common\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT_CommonHeader_Footer
    displayName: UAT_CommonHeader_Footer
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT_CommonHeader_Footer
        displayName: UAT_CommonHeader_Footer
        variables:
          - name: ArtifactName
            value: connectPortalCommonServices
          - name: Environment
            value: UAT
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\Common\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD_CommonHeader_Footer
    displayName: PROD_CommonHeader_Footer
    dependsOn: UAT_CommonHeader_Footer
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD_CommonHeader_Footer
        displayName: PROD_CommonHeader_Footer
        variables:
          - name: ArtifactName
            value: connectPortalCommonServices
          - name: Environment
            value: Prod
          - name: SiteName
            value: LogixServices
          - name: TargetFolder
            value: D:\AzureDevOps\LogixServices\Common\Release
          - name: WebAppPoolName
            value: LogixServices
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
