- name: Create a PowerShell script to delete old log files
  win_copy:
    content: |
      # Delete log files older than 3 days
      $path = "D:\logs\W3SVC1"
      Get-ChildItem -Path $path -Filter *.log | Where-Object { $_.LastWriteTime -lt (Get-Date).AddDays(-3) } | Remove-Item -Force
    dest: D:\scripts\delete_old_logs.ps1
