schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/ApplicationServices/LogixConnect-UserSync
  - name: api_sln
    value: LogixHealth.Connect.UserSync.sln
  - name: project_name
    value: LogixConnect-UserSync
  - name: artifactname_service
    value: ConnectUserSync
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
            path: s/LogixConnect
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_48_build.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    jobs:
      - deployment: DEV_ConnectUserSync
        displayName: DEV_ConnectUserSync
        variables:
          - name: ArtifactName
            value: ConnectUserSync
          - name: Environment
            value: Dev
          - name: TargetFolder
            value: D:\AzureDevOps\ConnectADUserSync\Release
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT_ConnectUserSync
        displayName: UAT_ConnectUserSync
        variables:
          - name: ArtifactName
            value: ConnectUserSync
          - name: Environment
            value: UAT
          - name: TargetFolder
            value: D:\
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: adfs
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    displayName: PROD
    dependsOn: UAT
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD_ConnectUserSync
        displayName: PROD_ConnectUserSync
        variables:
          - name: ArtifactName
            value: ConnectUserSync
          - name: Environment
            value: Prod
          - name: TargetFolder
            value: C:\
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: adfs
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
