FROM nginx:latest

# Ensure that the image is up to date.
RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Remove the default files in the nginx web root.
RUN rm -f /usr/share/nginx/html/*

# Copy the certificates to the container's web root.
COPY --chmod=644 ./html /usr/share/nginx/html/

# By default, nginx will not show a listing of the files in the web root directory. Thus, we have to
# create a custom configuration.
COPY --chmod=644 ./default.conf /etc/nginx/conf.d/default.conf

# Test the nginx config so that we can fail early.
RUN nginx -t

EXPOSE 80
