schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
stages:
  - stage: Build_RRE
    displayName: Build_RRE
    pool:
      name: Build
    variables:
      - name: api_directory
        value: platform/API/ApplicationServices/RREServiceandCoordinator
      - name: api_csproj_file
        value: LogixReconciler/LogixReconciler.csproj
      - name: test_csproj_file
        value: LogixReconcilerTest/LogixReconcilerTest.csproj
      - name: project_name
        value: RRE
      - name: artifactname_api
        value: LogixRRE
      - name: dotnet_version
        value: 8.x
    jobs:
      - job: Reconciler
        displayName: Reconciler
        steps:
          - checkout: self
            clean: true
            path: s/LogixRRE
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: Build_Coord
    displayName: Build_Coord
    pool:
      name: Build
    variables:
      - name: api_directory
        value: platform/API/ApplicationServices/RREServiceandCoordinator
      - name: api_csproj_file
        value: LogixCoordinator/LogixCoordinator.csproj
      - name: project_name
        value: Coordinator
      - name: artifactname_api
        value: LogixCoordinator
      - name: dotnet_version
        value: 8.x
    jobs:
      - job: Coordinator
        displayName: Coordinator
        steps:
          - checkout: self
            clean: true
            path: s/LogixCoordinator
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: DEV
    dependsOn: Build_Coord
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV_Reconciler
        displayName: DEV_Reconciler
        variables:
          - name: ArtifactName
            value: LogixRRE
          - name: ServiceName
            value: ReconcilerService
          - name: TargetFolder
            value: D:\TFS\Release
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: ICER-APP-DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
      - deployment: DEV_Coordinator
        displayName: DEV_Coordinator
        variables:
          - name: ArtifactName
            value: LogixCoordinator
          - name: ServiceName
            value: LogixCoordinator
          - name: TargetFolder
            value: D:\TFS\Release
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: ICER-APP-DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    dependsOn: Build_Coord
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT_Reconciler
        displayName: UAT_Reconciler
        variables:
          - name: ArtifactName
            value: LogixRRE
          - name: ServiceName
            value: ReconcilerService
          - name: TargetFolder
            value: D:\AzureDevOps\LogixRRE\Release
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: ICER-APP-UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
      - deployment: UAT_Coordinator
        displayName: UAT_Coordinator
        variables:
          - name: ArtifactName
            value: LogixCoordinator
          - name: ServiceName
            value: LogixCoordinator
          - name: TargetFolder
            value: D:\AzureDevOps\LogixCoordinator\Release
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: ICER-APP-UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    dependsOn: UAT
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD_Coordinator
        displayName: PROD_Coordinator
        variables:
          - name: ArtifactName
            value: LogixCoordinator
          - name: TargetFolder
            value: D:\AzureDevOps\LogixCoordinator\Release
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: coord
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
      - deployment: PROD_Reconciler
        displayName: PROD_Reconciler
        variables:
          - name: ArtifactName
            value: LogixRRE
          - name: TargetFolder
            value: D:\AzureDevOps\LogixRRE\Release
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: rre
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml

