- name: Ensure the Windows service is stopped
  win_service:
    name: "{{ item.service_name }}"
    state: stopped
  loop: "{{ windows_service_app_info }}"

- name: Set new service account credentials
  win_service:
    name: "{{ item.service_name }}"
    start_mode: auto
    username: "{{ item.gMSA }}"
  loop: "{{ windows_service_app_info }}"

- name: Start the Windows service
  win_service:
    name: "{{ item.service_name }}"
    state: started
  loop: "{{ windows_service_app_info }}"
