---
- name: Apply the following tasks
  hosts: web_saas_servers
  become: false
  gather_facts: true
  roles:
    # These 5 roles below will add a gMSA to an app pool with all required permissions
    - install_app_insights_agent
    - add_user_to_local_IIS_IUSRS
    - add_user_to_logon_as_a_batch_for_IIS_IUSRS
    - add_user_to_impersonate_client_after_auth
    - add_IIS_IUSRS_to_inetpub
    - apply_svcaccount_to_IIS_app_pool
    # - add_user_to_logon_as_a_batch_for_sched_task
    # - create_scheduled_task
    # - add_rewriteurl_rule
