steps:
  - task: CmdLine@2
    displayName: Ansible Apply
    inputs:
      script:
        'ansible-playbook 2_Product_Platforms/ansible/$(playbook_to_run) -i 2_Product_Platforms/ansible/inventory/$(inventory)
        --extra-vars "ansible_password=$(ansiblepw)
        az_arc_service_principal_id=$(az_arc_service_principal_id)
        az_arc_service_principal_secret=$(az_arc_service_principal_secret)
        az_arc_tenant_id=$(az_arc_tenant_id)
        az_arc_subscription_id=$(az_arc_subscription_id)
        az_arc_location=$(az_arc_location)
        azdo_agent_service_password=$(uat_azdo_agent_service_password)"'
