# schedules:
#   - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
#     displayName: Automated SonarQube Build
#     branches:
#       include:
#         - master
#     always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: dotnet_version
    value: 8.x
stages:
  - stage: Build_APP
    displayName: Build_APP
    pool:
      name: Build
    variables:
      - name: app_directory
        value: apps/mvc/LogixHRMS/LogixHealth.HID
      - name: project_name
        value: LogixHRMS-HID-App
      - name: app_csproj_file
        value: LogixHealth.HID.sln
      - name: container_path_app
        value: LogixHealth.HID
      - name: publish_appcsproj_file
        value: LogixHealth.HID/LogixHealth.HID.csproj
      - name: artifactname_app
        value: HID
    jobs:
      - job: HID_App
        displayName: HID_App
        steps:
          - checkout: self
            clean: true
            path: s/LogixHID_App
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.app_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: Build_API
    displayName: Build_API
    dependsOn: [] # Run this stage immediately (instead of being dependant upon the previous step).
    pool:
      name: Build
    variables:
      - name: project_name
        value: LogixHRMS-HID-Api
      - name: api_directory
        value: platform/API/ApplicationServices/LogixHRMS/LogixHIDApi
      - name: api_csproj_file
        value: LogixHealth.HID.Api/LogixHealth.HID.Api.csproj
      - name: container_path_api
        value: LogixHealth.HID.Api
      - name: publish_apicsproj_file
        value: LogixHealth.HID.Api.csproj
      - name: artifactname_api
        value: HIDApi
    jobs:
      - job: HID_Api
        displayName: HID_Api
        steps:
          - checkout: self
            clean: true
            path: s/LogixHID_Api
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: DEV_APP
    displayName: DEV_APP
    dependsOn: Build_APP
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        displayName: DEV
        variables:
          - name: ArtifactName
            value: HID
          - name: SiteName
            value: LogixHRMS
          - name: TargetFolder
            value: D:\TFS\LogixHRMS\LogixHID\Release
          - name: WebAppPoolName
            value: LogixHRMS
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: DEV_API
    displayName: DEV_API
    dependsOn: Build_API
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        displayName: DEV
        variables:
          - name: ArtifactName
            value: HIDApi
          - name: SiteName
            value: LogixHRMS
          - name: TargetFolder
            value: D:\TFS\LogixHRMS\LogixHIDApi\Release
          - name: WebAppPoolName
            value: LogixHRMS
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
