schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/Microservices/ApiPartners/LogixHealth.Micro.Partners.BcbsMa
  - name: api_csproj_file
    value: LogixHealth.Micro.Partners.BcbsMa.csproj
  - name: project_name
    value: Micro-ApiPartners-BCBSofMA
  - name: publish_apicsproj_file
    value: LogixHealth.Micro.Partners.BcbsMa.csproj
  - name: artifactname_api
    value: BCBSofMA
  - name: container_path_api
    value: LogixHealth.Micro.Partners.BcbsMa
  - name: test_csproj_file
    value: ../ApiPartners.BcbsofMA.MsTests/ApiPartners.BcbsofMA.MsTests.csproj
pool:
  name: Build
stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
            clean: true
            path: s/ApiPartners
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        variables:
          - name: ArtifactName
            value: BCBSofMA
          - name: SiteName
            value: apipartners.dmicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\AzureDevOps\APIServices\Microservice\ApiPartners\Release
          - name: WebAppPoolName
            value: bcbsma.dmicrosvc.apipartners
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        variables:
          - name: ArtifactName
            value: BCBSofMA
          - name: SiteName
            value: apipartners.umicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\AzureDevOps\APIServices\Microservice\ApiPartners\Release
          - name: WebAppPoolName
            value: bcbsma.umicrosvc.apipartners
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    displayName: PROD
    dependsOn: UAT
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD
        variables:
          - name: ArtifactName
            value: BCBSofMA
          - name: SiteName
            value: apipartners.microsvc.logixhealth.com
          - name: TargetFolder
            value: D:\AzureDevOps\APIServices\Microservice\ApiPartners\Release
          - name: WebAppPoolName
            value: bcbsma.microsvc.apipartners
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
