schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/Microservices/Remit
  - name: api_csproj_file
    value: LogixHealth.Microservice.Billing.DataAccess/LogixHealth.Microservice.Billing.DataAccess.csproj
  - name: project_name
    value: Micro-Billing-DataAccess
  - name: container_path_api
    value: LogixHealth.Microservice.Billing.DataAccess
  - name: publish_apicsproj_file
    value: LogixHealth.Microservice.Billing.DataAccess/LogixHealth.Microservice.Billing.DataAccess.csproj
  - name: artifactname_api
    value: Billing_DataAccess
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: Build
        steps:
          - checkout: self
            clean: true
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        variables:
          - name: ArtifactName
            value: Billing_DataAccess
          - name: SiteName
            value: billingdata.dmicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\AzureDevOps\APIServices\Microservice\BillingData\Release
          - name: WebAppPoolName
            value: billingdata.dmicrosvc.logixhealth.com
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        variables:
          - name: ArtifactName
            value: Billing_DataAccess
          - name: SiteName
            value: billingdata.umicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\AzureDevOps\APIServices\Microservice\BillingData\Release
          - name: WebAppPoolName
            value: billingdata.umicrosvc.logixhealth.com
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    displayName: PROD
    dependsOn: UAT
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD
        variables:
          - name: ArtifactName
            value: Billing_DataAccess
          - name: SiteName
            value: billingdata.microsvc.logixhealth.com
          - name: TargetFolder
            value: D:\AzureDevOps\APIServices\Microservice\BillingData\Release
          - name: WebAppPoolName
            value: billingdata.microsvc.logixhealth.com
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
