schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: ne(variables['Build.Reason'], 'Schedule')
  - name: api_directory
    value: platform/API/OrchestratorServices/Scheduler
  - name: api_csproj_file
    value: LogixHealth.Orchestration.Scheduler.sln
  - name: project_name
    value: Orchestrator-Scheduler
  - name: artifactname_api
    value: Scheduler
  - name: container_path_api
    value: LogixHealth.Orchestration.Scheduler
  - name: publish_apicsproj_file
    value: LogixHealth.Orchestration.Scheduler/LogixHealth.Orchestration.Scheduler.csproj
  - name: test_csproj_file
    value: LogixHealth.Orchestration.Scheduler.MsTest/LogixHealth.Orchestration.Scheduler.MsTest.csproj
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: OrchestratorScheduler
        displayName: Orchestrator-Scheduler
        steps:
          - checkout: self
            clean: true
            path: s/OrchestratorScheduler
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        displayName: DEV
        variables:
          - name: ArtifactName
            value: Scheduler
          - name: SiteName
            value: scheduler.dorchsvc.logixhealth.com
          - name: TargetFolder
            value: D:\TFS\MicroServices\Orchestrator\Scheduler\Release\
          - name: WebAppPoolName
            value: scheduler.dorchsvc.logixhealth.com
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    variables:
      - name: ArtifactName
        value: Scheduler
      - name: SiteName
        value: scheduler.uorchsvc.logixhealth.com
      - name: TargetFolder
        value: D:\TFS\MicroServices\Orchestrator\Scheduler\Release\
      - name: WebAppPoolName
        value: scheduler.uorchsvc.logixhealth.com
    jobs:
      - deployment: UAT
        displayName: UAT
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml