schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/OrchestratorServices/User
  - name: api_csproj_file
    value: LogixHealth.OrchestrationServices.User.sln
  - name: project_name
    value: Orch-User
  - name: artifactname_api
    value: OrchUser
  - name: container_path_api
    value: OrchestrationServices.User
  - name: dotnet_version
    value: 8.x
  - name: publish_apicsproj_file
    value: OrchestrationServices.User/LogixHealth.OrchestrationServices.User.csproj
  - name: test_csproj_file
    value: OrchestrationServices.User.Test/LogixHealth.OrchestrationServices.User.Test.csproj
pool:
  name: Build
stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
            clean: true
            path: s/User
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        variables:
          - name: ArtifactName
            value: OrchUser
          - name: SiteName
            value: user.dorchsvc.logixhealth.com
          - name: TargetFolder
            value: D:\AzureDevOps\APIServices\Orchestration\User\Release
          - name: WebAppPoolName
            value: user.dorchsvc.logixhealth.com
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        variables:
          - name: ArtifactName
            value: OrchUser
          - name: SiteName
            value: user.uorchsvc.logixhealth.com
          - name: TargetFolder
            value: D:\AzureDevOps\APIServices\Orchestration\User\Release
          - name: WebAppPoolName
            value: user.uorchsvc.logixhealth.com
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    displayName: PROD
    dependsOn: UAT
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD
        variables:
          - name: ArtifactName
            value: OrchUser
          - name: SiteName
            value: user.orchsvc.logixhealth.com
          - name: TargetFolder
            value: D:\AzureDevOps\APIServices\Orchestration\User\Release
          - name: WebAppPoolName
            value: user.orchsvc.logixhealth.com
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
