FROM ubuntu:latest

# Ensure that the image is up to date.
RUN DEBIAN_FRONTEND=noninteractive \
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy the LogixHealth root certificate.
COPY ./certs/BEDROOTCA001.crt /usr/local/share/ca-certificates/BEDROOTCA001.crt
RUN update-ca-certificates

# Copy the private key.
# TODO
