schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: autoproject
    value: EligibilityPlaywright
  - name: dtesturl
    value: 'https://deligibility.logixhealth.com'
  - name: qtesturl
    value: 'https://qeligibility.logixhealth.com'
  - name: utesturl
    value: 'https://ueligibility.logixhealth.com'
  - name: ptesturl
    value: 'https://eligibility.logixhealth.com'
  - name: RegressionSuite
    value: 'regression.xml'
  - name: SanitySuite
    value: 'sanity.xml'
  - name: dotnet_version
    value: 8.x
  - name: checkout_path
    value: LogixEligibility
  - name: dacpac_sqlproj_filepath
    value: db_scripts/LogixEligibility/LogixEligibility DB/LogixEligibility.sqlproj
  - name: Dacpack_ArtifactName
    value: Eligibility_Dacpac
trigger: none
stages:
  - stage: Build_APP
    displayName: Build_APP
    pool:
      name: Build
    variables:
      - name: app_directory
        value: apps/mvc/LogixEligibility
      - name: app_csproj_file
        value: LogixHealth.Eligibility.sln
      - name: project_name
        value: LogixEligibilityApp
      - name: container_path_app
        value: App/LogixHealth.Eligibility
      - name: publish_appcsproj_file
        value: LogixHealth.Eligibility/LogixHealth.Eligibility.csproj
      - name: publish_path_app
        value: APP
      - name: artifactname_app
        value: LogixEligibility
      - name: test_app_csproj_file
        value: LogixHealth.Service.Tests/LogixHealth.Service.Tests.csproj
    jobs:
      - job: EligibilityApp
        displayName: EligibilityApp
        steps:
          - checkout: self
            path: s/LogixEligibilityApp
            clean: true
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.app_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: Build_API
    displayName: Build_API
    dependsOn: [] # Run this stage immediately (instead of being dependant upon the previous step).
    pool:
      name: Build
    variables:
      - name: api_directory
        value: platform/API/ApplicationServices/LogixEligibility
      - name: api_csproj_file
        value: LogixHealth.Eligibility.API.sln
      - name: project_name
        value: LogixEligibilityApi
      - name: container_path_api
        value: API/LogixHealth.Eligibility.API
      - name: publish_apicsproj_file
        value: LogixHealth.Eligibility.API/LogixHealth.Eligibility.API.csproj
      - name: publish_path_api
        value: API
      - name: artifactname_api
        value: LogixEligibilityApi
      - name: test_csproj_file
        value: LogixHealth.Eligibility.Tests/LogixHealth.Eligibility.Tests.csproj
    jobs:
      - job: EligibilityApi
        displayName: EligibilityApi
        steps:
          - checkout: self
            path: s/LogixEligibilityApi
            clean: true
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml

  - stage: Build_DAC_PACK
    displayName: Build-DAC-PACK
    dependsOn: [] # Run this stage immediately (instead of being dependant upon the previous step).
    pool:
      name: Build
    jobs:
      - job: Build_DAC_PACK
        displayName: Build-DAC-PACK
        steps:
          - template: ../templates/Dacpac_build_template.yml
  - stage: DACPKDeployment_DEV
    displayName: DEV-DAC-PACK
    dependsOn: Build_DAC_PACK
    pool:
      name: DBA
      demands:
        - agent.name -equals BEDDSQL001
    jobs:
      - deployment: DEV
        environment: DEV
        variables:
          - name: DBServer
            value: BEDDSQL001
          - name: TargetFolder
            value: M:\DACPACK-solutions
          - name: Dacpack_ArtifactName
            value: Eligibility_Dacpac
          - name: Dacpac_file
            value: LogixEligibility.dacpac # give the sql filename ending with .dacpac instead of .sqlproj
          - name: xml_file
            value: LogixEligibility.publish.xml # give file name for your xml file
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/Dacpac_deployment_template.yml
  - stage: DEV_APP
    displayName: DEV_APP
    dependsOn: Build_APP
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        displayName: DEV
        variables:
          - name: ArtifactName
            value: LogixEligibility
          - name: SiteName
            value: LogixEligibility
          - name: TargetFolder
            value: D:\TFS\LogixEligibility\Release
          - name: WebAppPoolName
            value: LogixEligibility
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: billing
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: DEV_API
    displayName: DEV_API
    dependsOn: Build_API
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        displayName: DEV
        variables:
          - name: ArtifactName
            value: LogixEligibilityApi
          - name: SiteName
            value: LogixEligibility
          - name: TargetFolder
            value: D:\TFS\LogixEligibility\Release
          - name: WebAppPoolName
            value: LogixEligibility
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: billing-api
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: DACPKDeployment_UAT
    displayName: UAT-DAC-PACK
    dependsOn: Build_DAC_PACK
    pool:
      name: DBA
      demands:
        - agent.name -equals BEDDSQL001
    jobs:
      - deployment: UAT
        environment: UAT
        variables:
          - name: DBServer
            value: BEDUSQL001
          - name: TargetFolder
            value: M:\DACPACK-solutions
          - name: Dacpack_ArtifactName
            value: Eligibility_Dacpac
          - name: Dacpac_file
            value: LogixEligibility.dacpac # give the sql filename ending with .dacpac instead of .sqlproj
          - name: xml_file
            value: LogixEligibility.publish.xml # give file name for your xml file
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/Dacpac_deployment_template.yml
  - stage: UAT_APP
    displayName: UAT_APP
    dependsOn: Build_APP
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        displayName: UAT
        variables:
          - name: ArtifactName
            value: LogixEligibility
          - name: SiteName
            value: LogixEligibility
          - name: TargetFolder
            value: D:\TFS\LogixEligibility\Release
          - name: WebAppPoolName
            value: LogixEligibility
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: billing
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT_API
    displayName: UAT_API
    dependsOn: Build_API
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        displayName: UAT
        variables:
          - name: ArtifactName
            value: LogixEligibilityApi
          - name: SiteName
            value: LogixEligibility
          - name: TargetFolder
            value: D:\TFS\LogixEligibility\Release
          - name: WebAppPoolName
            value: LogixEligibility
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: billing-api
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: DACPKDeployment_PROD
    displayName: PROD-DAC-PACK
    dependsOn: DACPKDeployment_UAT
    pool:
      name: DBA
      demands:
        - agent.name -equals BEDDSQL001
    jobs:
      - deployment: PROD
        environment: PROD
        variables:
          - name: DBServer
            value: BEDSQLLC02
          - name: TargetFolder
            value: M:\DACPACK-solutions
          - name: Dacpack_ArtifactName
            value: Eligibility_Dacpac
          - name: Dacpac_file
            value: LogixEligibility.dacpac # give the sql filename ending with .dacpac instead of .sqlproj
          - name: xml_file
            value: LogixEligibility.publish.xml # give file name for your xml file
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/Dacpac_deployment_template.yml
  - stage: PROD_APP
    displayName: PROD_APP
    dependsOn: UAT_APP
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD
        displayName: PROD
        variables:
          - name: ArtifactName
            value: LogixEligibility
          - name: SiteName
            value: LogixEligibility
          - name: TargetFolder
            value: D:\TFS\LogixEligibility\Release
          - name: WebAppPoolName
            value: LogixEligibility
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: billing
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD_API
    displayName: PROD_API
    dependsOn: UAT_API
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD
        displayName: PROD
        variables:
          - name: ArtifactName
            value: LogixEligibilityApi
          - name: SiteName
            value: LogixEligibility
          - name: TargetFolder
            value: D:\TFS\LogixEligibility\Release
          - name: WebAppPoolName
            value: LogixEligibility
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: billing-api
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
