- name: Set TLS version to 1.2 for HTTPS connections
  win_shell: "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12"

- name: Download Python installer
  win_get_url:
    url: https://www.python.org/ftp/python/3.13.0/python-3.13.0-amd64.exe
    dest: C:\temp\python-installer.exe
