trigger:
  paths:
    include:
      - 2_Product_Platforms/dev_lz/* # Note that changes to the L0 templates won't trigger any pipeline runs.

# IMPORTANT: For new pipelines, add build validation policy to master branch based on this pipeline with the above path filters.

pool: Build

stages:
  - template: ../../../0_Global_Library/pipeline-templates/pipeline-template.yml
    parameters:
      config:
        isDeploy: true
        destroyAbsentResources: false
        environment: AzureGlobalInfraL1
      components:
        - name: "DeployToSubScope"
          deploymentScope: "subscription"
          subscriptionId: "1f05644e-f734-46ef-abb5-0fea35e3f76e"
          serviceConnectionName: "LH Corp Dev 002"
          type: Bicep.V1
          templateDirectory: "2_Product_platforms/dev_lz/infrastructure"
          module: "sub"
          location: eastus
          tests:
            - name: Bicep Validate and What-If
              type: Bicep.V1
          state: present
