# This template installs Terraform using the `TerraformInstaller` task:
# https://github.com/jason-johnson/azure-pipelines-tasks-terraform/blob/main/overview.md

# It abstracts away:
# - Specifying the version of Terraform. (If "latest" is specified, then version 1.1.6 will be
#   used instead of the actual latest version.)
# - Setting the path to the LogixHealth self-signed certificate. (If this is not specified,
#   installation will fail.)

# Note that this template can only be used on Linux Agents since:
# - The path to the certificate is in Linux form.
# - Windows agents do not need to specify a custom certificate at all for some reason. See v1 of
#   this task for Windows agents.

steps:
  # Using `TerraformInstaller@2` does not work, even though the documentation says it should.
  - task: TerraformInstaller@1
    displayName: install terraform
    inputs:
      # 1.9.5 is the latest version as of August 29th, 2024.
      # https://github.com/hashicorp/terraform/releases
      terraformVersion: 1.9.5
    env:
      NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/BEDROOTCA001.crt
