schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
parameters:
  - name: Environment
    type: string
    default: development
    values:
      - development
      - uat
      - prod
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: buildConfiguration
    value: Release
  - name: api_directory
    value: platform/API/Microservices/Notify
  - name: api_csproj_file
    value: LogixHealth.Microservice.Notify/LogixHealth.Microservice.Notify.csproj
  - name: project_name
    value: Microservices-Notify
  - name: artifactname_api
    value: Notify
  - name: container_path_api
    value: LogixHealth.Microservice.Notify
  - name: test_csproj_file
    value: Logixhealth.Microservice.Notify.Test/Logixhealth.Microservice.Notify.Test.csproj
  - name: publish_apicsproj_file
    value: LogixHealth.Microservice.Notify/LogixHealth.Microservice.Notify.csproj
  - name: EF_sln
    value: yes
  - name: buildEnvironment
    value: ${{ parameters.Environment }}
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: Notify
        displayName: Notify
        steps:
          - checkout: self
            clean: true
            path: s/Notify
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: EFDevDeployment
    displayName: EF-Deploy-Dev
    dependsOn: Build
    pool:
      name: DBA
      demands:
        - agent.name -equals BEDSQLBK001
    jobs:
      - deployment: DEV
        environment: DEV
        variables:
          - name: databaseName
            value: logixoltp
          - name: scriptPaths
            value: E:\DB-solutions\Dev\Efbundle\script.sql
          - name: servers
            value: BEDDSQL001
          - name: Download_Path
            value: E:\DB-solutions\Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/EF_SQl_Script_Execution.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        variables:
          - name: ArtifactName
            value: Notify
          - name: SiteName
            value: notify.dmicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\TFS\MicroServices\Atomic\Notify\Release
          - name: WebAppPoolName
            value: notify.dmicrosvc.logixhealth.com
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: EFUATDeployment
    displayName: EF-Deploy-UAT
    dependsOn: Build
    pool:
      name: DBA
      demands:
        - agent.name -equals BEDSQLBK001
    jobs:
      - deployment: UAT
        environment: UAT
        variables:
          - name: databaseName
            value: logixoltp
          - name: scriptPaths
            value: E:\DB-solutions\UAT\Efbundle\script.sql
          - name: servers
            value: BEDUSQL001
          - name: Download_Path
            value: E:\DB-solutions\UAT
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/EF_SQl_Script_Execution.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        variables:
          - name: ArtifactName
            value: Notify
          - name: SiteName
            value: notify.umicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\TFS\MicroServices\Atomic\Notify\Release
          - name: WebAppPoolName
            value: notify.umicrosvc.logixhealth.com
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: EFProdDeployment
    displayName: EF-Deploy-Prod
    dependsOn: Build
    pool:
      name: DBA
      demands:
        - agent.name -equals BEDSQLBK001
    jobs:
      - deployment: Prod
        environment: Prod
        variables:
          - name: databaseName
            value: logixoltp
          - name: scriptPaths
            value: E:\DB-solutions\Prod\Efbundle\script.sql
          - name: servers
            value: BEDSQLLC02
          - name: Download_Path
            value: E:\DB-solutions\Prod
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/EF_SQl_Script_Execution.yml
  - stage: PROD
    displayName: PROD
    dependsOn: UAT
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD
        variables:
          - name: ArtifactName
            value: Notify
          - name: SiteName
            value: notify.microsvc.logixhealth.com
          - name: TargetFolder
            value: D:\TFS\MicroServices\Atomic\Notify\Release
          - name: WebAppPoolName
            value: notify.microsvc.logixhealth.com
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
