schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/Microservices/LOGGER
  - name: api_csproj_file
    value: LogixHealth.Microservices.Logger.sln
  - name: project_name
    value: MicroService_Logger
  - name: test_csproj_file
    value: LogixHealth.Microservices.Logger.Test/LogixHealth.Microservices.Logger.Test.csproj
  - name: artifactname_api
    value: Logger
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: MicroService_Logger
        displayName: MicroService_Logger
        steps:
          - checkout: self
            clean: true
            path: s/MicroService_Logger
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        displayName: DEV
        variables:
          - name: ArtifactName
            value: Logger
          - name: SiteName
            value: logger.dmicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\TFS\MicroServices\Atomic\Logger\Release
          - name: WebAppPoolName
            value: logger.dmicrosvc.logixhealth.com
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        displayName: UAT
        variables:
          - name: ArtifactName
            value: Logger
          - name: SiteName
            value: logger.umicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\TFS\MicroServices\Atomic\Logger\Release
          - name: WebAppPoolName
            value: logger.umicrosvc.logixhealth.com
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    displayName: PROD
    dependsOn: UAT
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD
        displayName: PROD
        variables:
          - name: ArtifactName
            value: Logger
          - name: SiteName
            value: logger.microsvc.logixhealth.com
          - name: TargetFolder
            value: D:\TFS\Services\Micro
          - name: WebAppPoolName
            value: logger.microsvc.logixhealth.com
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
