schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
parameters:
  - name: Environment
    type: string
    default: development
    values:
      - development
      - uat
      - prod
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/Microservices/CPM/
  - name: api_csproj_file
    value: LogixHealth.Microservice.CPM/LogixHealth.Microservice.CPM.csproj
  - name: project_name
    value: Microservices-CPM
  - name: test_csproj_file
    value: LogixHealth.Microservice.CPM.Test/LogixHealth.Microservice.CPM.Test.csproj
  - name: container_path_api
    value: LogixHealth.Microservice.CPM
  - name: publish_apicsproj_file
    value: LogixHealth.Microservice.CPM/LogixHealth.Microservice.CPM.csproj
  - name: artifactname_api
    value: CPM
  - name: dotnet_version
    value: 8.x
  - name: EF_sln
    value: yes
  - name: buildEnvironment
    value: ${{ parameters.Environment }}
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build

    jobs:
      - job: CPM
        displayName: CPM
        steps:
          - checkout: self
            clean: true
            path: s/CPM
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: EFDeployment_DEV
    displayName: EF-Deploy-Dev
    dependsOn: Build
    pool:
      name: DBA
      demands:
        - agent.name -equals BEDSQLBK001
    jobs:
      - deployment: DEV
        environment: DEV
        variables:
          - name: databaseName
            value: logixoltp
          - name: scriptPaths
            value: E:\DB-solutions\Dev\Efbundle\script.sql
          - name: servers
            value: BEDDSQL001
          - name: Download_Path
            value: E:\DB-solutions\Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/EF_SQl_Script_Execution.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        variables:
          - name: ArtifactName
            value: CPM
          - name: SiteName
            value: cpm.dmicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\TFS\MicroServices\Atomic\CPM\Release
          - name: WebAppPoolName
            value: cpm.dmicrosvc.logixhealth.com
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: EFDeployment_UAT
    displayName: EF-Deploy-UAT
    dependsOn: Build
    pool:
      name: DBA
      demands:
        - agent.name -equals BEDSQLBK001
    jobs:
      - deployment: UAT
        environment: UAT
        variables:
          - name: databaseName
            value: logixoltp
          - name: scriptPaths
            value: E:\DB-solutions\Dev\Efbundle\script.sql
          - name: servers
            value: BEDUSQL001
          - name: Download_Path
            value: E:\DB-solutions\Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/EF_SQl_Script_Execution.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    variables:
      - name: ArtifactName
        value: CPM
      - name: SiteName
        value: cpm.umicrosvc.logixhealth.com
      - name: TargetFolder
        value: D:\TFS\MicroServices\Atomic\CPM\Release\
      - name: WebAppPoolName
        value: cpm.umicrosvc.logixhealth.com
    jobs:
      - deployment: UAT
        displayName: UAT
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: EFDeployment_PROD
    displayName: EF-Deploy-PROD
    dependsOn: EFDeployment_UAT
    pool:
      name: DBA
      demands:
        - agent.name -equals BEDSQLBK001
    jobs:
      - deployment: PROD
        environment: PROD
        variables:
          - name: databaseName
            value: logixoltp
          - name: scriptPaths
            value: E:\DB-solutions\Dev\Efbundle\script.sql
          - name: servers
            value: BEDSQLLC02
          - name: Download_Path
            value: E:\DB-solutions\Dev
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/EF_SQl_Script_Execution.yml
  - stage: PROD
    displayName: PROD
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    variables:
      - name: ArtifactName
        value: CPM
      - name: SiteName
        value: cpm.microsvc.logixhealth.com
      - name: TargetFolder
        value: D:\TFS\MicroServices\Atomic\CPM\Release\
      - name: WebAppPoolName
        value: cpm.microsvc.logixhealth.com
    jobs:
      - deployment: PROD_1
        displayName: PROD-1
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
