schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/Microservices/WFM
  - name: api_csproj_file
    value: LogixHealth.Microservice.WFM/LogixHealth.Microservice.WFM.sln
  - name: project_name
    value: Micro-WFM
  - name: artifactname_api
    value: WFM
  - name: publish_apicsproj_file
    value: LogixHealth.Microservice.WFM/LogixHealth.Microservice.WFM.csproj
  - name: dotnet_version
    value: 8.x
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: WFM
        displayName: WFM
        steps:
          - checkout: self
            clean: true
            path: s/WFM
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        variables:
          - name: ArtifactName
            value: WFM
          - name: SiteName
            value: wfm.dmicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\TFS\MicroServices\Atomic\WFM\Release
          - name: WebAppPoolName
            value: wfm.dmicrosvc.logixhealth.com
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        variables:
          - name: ArtifactName
            value: WFM
          - name: SiteName
            value: wfm.umicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\TFS\MicroServices\Atomic\WFM\Release
          - name: WebAppPoolName
            value: wfm.umicrosvc.logixhealth.com
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
