# schedules:
#   - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
#     displayName: Automated SonarQube Build
#     branches:
#       include:
#         - master
#     always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: and(ne(variables['Build.Reason'], 'Schedule'), succeeded())
  - name: api_directory
    value: platform/API/Microservices/Intelligence
  - name: api_csproj_file
    value: LogixHealth.Microservice.Intelligence/LogixHealth.Microservice.Intelligence.csproj
  - name: project_name
    value: Microservices-Intelligence
  - name: publish_apicsproj_file
    value: LogixHealth.Microservice.Intelligence/LogixHealth.Microservice.Intelligence.csproj
  - name: artifactname_api
    value: INTELL
  - name: container_path_api
    value: LogixHealth.Microservice.intelligence
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: INTELL
        displayName: INTELL
        steps:
          - checkout: self
            clean: true
            path: s/Intelligence
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}
          - template: ../templates/dotnetframework_8_build.yml
  - stage: DEV
    displayName: DEV
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        displayName: DEV
        variables:
          - name: ArtifactName
            value: INTELL
          - name: SiteName
            value: intell.dmicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\TFS\MicroServices\Atomic\INTELL\Release
          - name: WebAppPoolName
            value: intell.dmicrosvc.logixhealth.com
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        displayName: UAT
        variables:
          - name: ArtifactName
            value: INTELL
          - name: SiteName
            value: intell.umicrosvc.logixhealth.com
          - name: TargetFolder
            value: D:\TFS\MicroServices\Atomic\INTELL\Release
          - name: WebAppPoolName
            value: intell.umicrosvc.logixhealth.com
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: MicroSVC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
