schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: ne(variables['Build.Reason'], 'Schedule')
  - name: feedName
    value: LogixLibrary
  - name: api_directory
    value: platform/Libraries/
trigger: none
stages:
  - stage: Build
    displayName: Build
    pool:
      name: Build
    jobs:
      - job: ELStandard
        displayName: EL-Standard
        steps:
          - checkout: self
            path: s/EL
          - template: ../templates/prebuild_validation.yml
            parameters:
              directoryPaths:
                - ${{ variables.api_directory }}

          - task: DotNetCoreCLI@2
            displayName: 'dotnet Restore EL-Standard'
            inputs:
              command: restore
              projects: ${{ variables.api_directory }}/LogixHealth.EnterpriseLibraries.sln
          - task: SonarQubePrepare@5
            condition: ${{ variables.SonarQube_Condition }}
            inputs:
              SonarQube: SonarQube New
              projectKey: 'EL-Standard'
              projectName: 'EL-Standard'
              projectVersion: 'EL-Standard-Master'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: '${{ variables.api_directory }}/LogixHealth.EnterpriseLibraries.sln'
              arguments: '--warnaserror'
          - task: SonarQubeAnalyze@5
            condition: ${{ variables.SonarQube_Condition }}
          - task: SonarQubePublish@5
            condition: ${{ variables.SonarQube_Condition }}
          - task: sonar-buildbreaker@8
            inputs:
              SonarQube: SonarQube New
            continueOnError: true
          - task: DotNetCoreCLI@2
            displayName: 'Dotnet Net8Pack'
            inputs:
              command: 'pack'
              packagesToPack: '${{ variables.api_directory }}/**/*.csproj;!${{ variables.api_directory }}/**/*.Test.csproj'
              versioningScheme: 'byEnvVar'
              versionEnvVar: 'AssemblyVersion'
          - task: DotNetCoreCLI@2
            displayName: 'Dotnet Net8Push'
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: $(feedName)
          - template: ../templates/remove_sonarqube.yml
          - template: ../templates/delete_build_files.yml
