schedules:
  - cron: 0 0 * * 6 # Every Saturday at midnight UTC time
    displayName: Automated SonarQube Build
    branches:
      include:
        - master
    always: true
variables:
  - name: SonarQube_Condition
    value: contains(variables['Build.SourceBranch'], 'refs/heads/master')
  - name: build_reason_condition
    value: ne(variables['Build.Reason'], 'Schedule')
  - name: api_directory
    value: platform/API/ApplicationServices/LogixRecruitment-api
  - name: app_directory
    value: apps/mvc/LogixRecruitment
  - name: project_name
    value: LogixRecruitment
  - name: app_sln
    value: LogixHealth.Recruitment.sln
  - name: container_path_app
    value: APP/LogixHealth.Recruitment
  - name: container_path_service
    value: Api/LogixHealth.Recruitment.Api
  - name: publish_path_app
    value: APP
  - name: publish_path_api
    value: Api
  - name: publish_appcsproj_file
    value: LogixHealth.Recruitment/LogixHealth.Recruitment.csproj
  - name: publish_apicsproj_file
    value: LogixHealth.Recruitment.Api/LogixHealth.Recruitment.Api.csproj
  - name: artifactname_app
    value: Recruitment
  - name: artifactname_service
    value: RecruitmentApi
  - name: lib_directory
    value: platform/Libraries/netCore22
stages:
  - stage: Build
    pool:
      name: Build
    jobs:
      - job: Recruitment
        displayName: Recruitment
        steps:
          - checkout: self
            clean: true
            path: s/LogixRecruitment
          - template: ../templates/dotnetframework_48_build.yml
  - stage: Dev
    displayName: DEV
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: DEV
        variables:
          - group: LogixRecruitment-Dev
        environment:
          name: DEV
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: UAT
    displayName: UAT
    dependsOn: Build
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: UAT
        variables:
          - group: LogixRecruitment-UAT
        environment:
          name: UAT
          resourceType: virtualMachine
          tags: saas
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
  - stage: PROD
    displayName: PROD
    dependsOn: UAT
    condition: ${{ variables.build_reason_condition }}
    jobs:
      - deployment: PROD
        variables:
          - group: LogixRecruitment-PROD
        environment:
          name: PROD
          resourceType: virtualMachine
          tags: ops
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../templates/DownloadArtifact.yml
