ansible_user: svc_ansible@CORP.LOGIXHEALTH.LOCAL
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_transport: kerberos
ansible_winrm_server_cert_validation: ignore
ansible_winrm_kerberos_delegation: true
az_arc_location: eastus
